namespace Console.Flow;

// Шаги диалогового потока с пользователем
public enum UserFlowStep
{
    None = 0,
    WaitingAmount = 1,
    ChoosingCategory = 2,
    WaitingDescription = 3,
    WaitingGoalName = 4,
    WaitingGoalTarget = 5,
    WaitingGoalDeadline = 6,
    WaitingGoalDeposit = 7,
    WaitingGoalWithdraw = 8,
    WaitingGoalSelect = 9,
    WaitingGoalEditName = 10,
    WaitingGoalEditAmount = 11,
    WaitingGoalEditDeadline = 12,
    WaitingDebtName = 13,
    WaitingDebtAmount = 14,
    WaitingDebtType = 15,
    WaitingDebtDeadline = 16,
    WaitingDebtPayment = 17,
    WaitingDebtDescription = 18,
    WaitingDebtSelect = 19,
    WaitingDebtEditName = 20,
    WaitingDebtEditDeadline = 21,
    WaitingDebtEditDesc = 22,
    WaitingRegularName = 23,
    WaitingRegularAmount = 24,
    WaitingRegularFrequency = 25,
    WaitingRegularDate = 26,
    WaitingRegularSelect = 27,
    WaitingRegularEditName = 28,
    WaitingRegularEditAmount = 29,
    WaitingRegularEditDay = 30,
    WaitingRegularEditCat = 31,
    WaitingLimitCategory = 32,
    WaitingLimitAmount = 33,
    WaitingNewCategory = 34
}